### PR TITLE
updated all js files to tsx files

### PR DESCRIPTION
**Pull request by sid-nc**
issue : convert everything to typescript

### CODE REVIEW

**Comment by volt-roy** [comment]
@sid-nc did you just name all the files with .tsx extension

**Comment by sid-nc** [comment]
no 
i did change js files to tsx files

**Comment by sid-nc** [comment]
i made changes to all the files and uploaded the pull request as a repo by comapring it with the original repo. I guess the changes did not get reflected

**Comment by sid-nc** [comment]
the changes are actually reflected. if you could kindly take a look at index.tsx, app.tsx , etc and let me know

**Pull request merged**
